PaupWebDucan/Controllers/KategorijeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PaupWebDucan.Misc;
using PaupWebDucan.Models;

namespace PaupWebDucan.Controllers
{
    [Authorize(Roles =OvlastiKorisnik.Administator + "," + OvlastiKorisnik.Moderator)]
    public class KategorijeController : Controller
    {
        private BazaDbContext db = new BazaDbContext();

        // GET: Kategorije
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.PopisKategorija.ToList());
        }

        // GET: Kategorije/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategorije kategorije = db.PopisKategorija.Find(id);
            if (kategorije == null)
            {
                return HttpNotFound();
            }
            return View(kategorije);
        }

        // GET: Kategorije/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kategorije/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaterijalIzrade,NazivKategorije,ZastarjeliModel")] Kategorije kategorije)
        {
            if (ModelState.IsValid)
            {
                db.PopisKategorija.Add(kategorije);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kategorije);
        }

        // GET: Kategorije/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategorije kategorije = db.PopisKategorija.Find(id);
            if (kategorije == null)
            {
                return HttpNotFound();
            }
            return View(kategorije);
        }

        // POST: Kategorije/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaterijalIzrade,NazivKategorije,ZastarjeliModel")] Kategorije kategorije)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kategorije).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kategorije);
        }

        // GET: Kategorije/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategorije kategorije = db.PopisKategorija.Find(id);
            if (kategorije == null)
            {
                return HttpNotFound();
            }
            return View(kategorije);
        }

        // POST: Kategorije/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var proizvod = db.PopisProizvodaBaze.FirstOrDefault(x => x.KategorijeSifra == id);

            Kategorije kategorije = db.PopisKategorija.Find(id);
            if (proizvod == null)
            {
                db.PopisKategorija.Remove(kategorije);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PaupWebDucan/Controllers/ProizvodiController.cs
using PaupWebDucan.Models;
using PaupWebDucan.Reports;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PaupWebDucan.Controllers
{
    [Authorize]
    public class ProizvodiController : Controller
    {
        BazaDbContext bazaPodataka = new BazaDbContext();
        // GET: Proizvodi
        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.Title = "Početna stranica sa proizvodima";
            ViewBag.Skladiste = "Skladiste PAUP (Posebnih asortimana u prodaji)";
            return View();
        }

        //Popis
        [AllowAnonymous]
        public ActionResult PopisProizvoda(string naziv, string ostecen, string kategorija)
        {
            var proizvodi = bazaPodataka.PopisProizvodaBaze.ToList();

            var kategorijeList = bazaPodataka.PopisKategorija.OrderBy(x => x.NazivKategorije).ToList();
            ViewBag.NazivKategorije = kategorijeList;

            if (!string.IsNullOrWhiteSpace(naziv))
            {
                proizvodi = proizvodi.Where(x=> x.ImeKontrolniBroj.ToUpper().Contains(naziv.ToUpper())).ToList();
            }
            if (!string.IsNullOrWhiteSpace(ostecen))
            {
                proizvodi = proizvodi.Where(x => x.Ostecen == ostecen).ToList();
            }
            if (!string.IsNullOrWhiteSpace(kategorija))
            {
                proizvodi = proizvodi.Where(x=>x.KategorijeSifra == kategorija).ToList();
            }

            if (proizvodi.Count == 0)
            {
                ViewBag.Poruka = "Nema rezultata pretraživanja.";
            }
            else
            {
                ViewBag.Poruka = string.Empty;
            }

            return View(proizvodi);
        }


        //Detalji
        public ActionResult Detalji(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction("PopisProizvoda");
            }

            Proizvod proizvod = bazaPodataka.PopisProizvodaBaze.FirstOrDefault(x => x.SkladisniBroj == id);

            if (proizvod == null)
            {
                return RedirectToAction("PopisProizvoda");
            }
            return View(proizvod);
        }


        //Azuriraj
        public ActionResult Azuriraj(int? id)
        {
            Proizvod proizvod = null;

            if(!id.HasValue)
            {
                proizvod = new Proizvod();
                ViewBag.Title = "Unos novog proizvoda";
                ViewBag.NoviProizvod = true;
            }
            else
            {
                proizvod = bazaPodataka.PopisProizvodaBaze.FirstOrDefault(x => x.SkladisniBroj == id);
                //ako u listi nema proizvoda sa trazenim skladisnim brojem onda je varijabla Skladisni broj null
                if (proizvod == null)
                {
                    return HttpNotFound();
                }
                ViewBag.Title = "Ažuriranje podataka o proizvodu";
                ViewBag.NoviProizvod = false;
            }

            var proizvodi = bazaPodataka.PopisKategorija.OrderBy(x => x.NazivKategorije).ToList();
            proizvodi.Insert(0, new Kategorije { MaterijalIzrade = "",NazivKategorije="Nedefinirano" });
            ViewBag.Kategorije = proizvodi;

            return View(proizvod);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Azuriraj(Proizvod p)
        {
            //Validacija kontrolnog broja
            if (!KontrolniBroj.JeValidanKontrolniBroj(p.KontrolniBroj))
            {
                ModelState.AddModelError("Kontrolni broj", "Neispravan kontrolni broj.");
            }
            //Kraj validacije

            if (p.ImageFile !=null)
            {
                string fileName = Path.GetFileNameWithoutExtension(p.ImageFile.FileName);
                string extension = Path.GetExtension(p.ImageFile.FileName);

                if (extension == ".jpg" || extension == ".jpeg" || extension == ".png")
                {
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    p.SlikaPutanja = "~/Images/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Images/"),fileName);
                    p.ImageFile.SaveAs(fileName);
                }
                else
                {
                    ModelState.AddModelError("SlikaPutanja", "Nepodržana ekstenzija");
                }
            }



            if (ModelState.IsValid)
            {
                if(p.SkladisniBroj != 0)
                {
                    bazaPodataka.Entry(p).State = System.Data.Entity.EntityState.Modified;
                }
                else
                {
                    bazaPodataka.PopisProizvodaBaze.Add(p);
                }
                    bazaPodataka.SaveChanges();

                return RedirectToAction("PopisProizvoda");
            }

            if(p.SkladisniBroj == 0)
            {
                ViewBag.Title = "Unos novog proizvoda";
                ViewBag.NoviProizvod = true;
            }
            else
            {
                ViewBag.Title = "Ažuriranje podataka o proizvodu";
                ViewBag.NoviProizvod = false;
            }

            var proizvodi = bazaPodataka.PopisKategorija.OrderBy(x => x.NazivKategorije).ToList();
            proizvodi.Insert(0, new Kategorije { MaterijalIzrade = "", NazivKategorije = "Nedefinirano" });
            ViewBag.Kategorije = proizvodi;


            return View(p);
        }




        //Brisi
        public ActionResult Brisi(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("PopisProizvoda");
            }
            Proizvod p = bazaPodataka.PopisProizvodaBaze.FirstOrDefault(x => x.SkladisniBroj == id);

            if(p == null)
            {
                return HttpNotFound();
            }
            ViewBag.Title = "Potvrda brisanja proizvoda";
            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Brisi(int id)
        {
            Proizvod p = bazaPodataka.PopisProizvodaBaze.FirstOrDefault(x => x.SkladisniBroj == id);
            if (p == null)
            {
                return HttpNotFound();
            }

            bazaPodataka.PopisProizvodaBaze.Remove(p);
            bazaPodataka.SaveChanges();

            return View("BrisiStatus");
        }

        public ActionResult IspisPDF(string naziv, string ostecen, string kategorija)
        {
            var proizvodi = bazaPodataka.PopisProizvodaBaze.ToList();

            if (!string.IsNullOrWhiteSpace(naziv))
            {
                proizvodi = proizvodi.Where(x => x.ImeKontrolniBroj.ToUpper().Contains(naziv.ToUpper())).ToList();
            }
            if (!string.IsNullOrWhiteSpace(ostecen))
            {
                proizvodi = proizvodi.Where(x => x.Ostecen == ostecen).ToList();
            }
            if (!string.IsNullOrWhiteSpace(kategorija))
            {
                proizvodi = proizvodi.Where(x => x.KategorijeSifra == kategorija).ToList();
            }

            if (proizvodi.Count == 0)
            {
                ViewBag.Poruka = "Nema rezultata pretraživanja.";
            }
            else
            {
                ViewBag.Poruka = string.Empty;
            }

            ProizvodiReport proizvodiReport = new ProizvodiReport();
            proizvodiReport.ListaProizvoda(proizvodi);

            return File(proizvodiReport.Podaci, System.Net.Mime.MediaTypeNames.Application.Pdf, "PopisProizvoda.pdf");
        }
    }
}

PaupWebDucan/Views/Shared/_Layout.cshtml
@using PaupWebDucan.Misc
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Skladiste - Skladiste PAUP (Posebnih asortimana u prodaji)</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">
                Skladiste PAUP (Posebnih asortimana u prodaji)
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Početna", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Proizvodi u skladištu", "Index", "Proizvodi", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Kategorije proizvoda", "Index", "Kategorije", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    @if (User.Identity.IsAuthenticated && (User as LogiraniKorisnik).IsInRole(OvlastiKorisnik.Administator))
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Korisnici", "Index", "Korisnici", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            @Html.ActionLink(((User as LogiraniKorisnik).PrezimeIme), "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Odjava", "Odjava", "Korisnici", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            @Html.ActionLink("Prijava", "Prijava", "Korisnici", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Vrlec Mirko @DateTime.Now.Year - Skladiste PAUP (Posebnih asortimana u prodaji)</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>